version: 2.1

orbs:
  node: circleci/node@4.7
jobs:
  run-tests:
    docker:
      - image: cimg/node:16.10
        environment:
          NODE_ENV: test
          TEST_POSTGRES_USER: $TEST_POSTGRES_USER
          TEST_POSTGRES_PASSWORD: $TEST_POSTGRES_PASSWORD
          TEST_POSTGRES_HOST: $TEST_POSTGRES_HOST
          TEST_POSTGRES_DB: $TEST_POSTGRSE_DB
          TEST_POSTGRES_PORT: $TEST_POSTGRES_PORT
          API_PORT: $API_PORT
      - image: cimg/postgres:13.5
        environment:
          POSTGRES_USER: $TEST_POSTGRES_USER
          POSTGRES_DB: $TEST_POSTGRES_DB
          POSTGRES_PASSWORD: $TEST_POSTGRES_PASSWORD
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Run migrations
          command: npm run migration:test:up
      - run:
          name: Run tests
          command: npm run test:ci

workflows:
  ci_pipeline:
    jobs:
      - run-tests
